-- Tabla para almacenar configuraciones encriptadas (API keys, etc.)
-- Esta tabla solo es accesible por administradores

CREATE TABLE IF NOT EXISTS configuraciones (
  id bigint generated by default as identity primary key,
  clave text not null unique, -- Ej: 'gemini_api_key'
  valor_encriptado text not null, -- Valor encriptado
  descripcion text,
  creado_por uuid references perfiles(id),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Índice para búsquedas rápidas
CREATE INDEX IF NOT EXISTS idx_configuraciones_clave ON configuraciones(clave);

-- Política RLS: Solo admins pueden ver y modificar configuraciones
ALTER TABLE configuraciones ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Solo admins pueden ver configuraciones"
  ON configuraciones FOR SELECT
  USING (
    exists (
      select 1 from perfiles
      where perfiles.id = auth.uid()
      and perfiles.rol = 'admin'
    )
  );

CREATE POLICY "Solo admins pueden insertar configuraciones"
  ON configuraciones FOR INSERT
  WITH CHECK (
    exists (
      select 1 from perfiles
      where perfiles.id = auth.uid()
      and perfiles.rol = 'admin'
    )
  );

CREATE POLICY "Solo admins pueden actualizar configuraciones"
  ON configuraciones FOR UPDATE
  USING (
    exists (
      select 1 from perfiles
      where perfiles.id = auth.uid()
      and perfiles.rol = 'admin'
    )
  );

-- Función para actualizar updated_at
CREATE OR REPLACE FUNCTION update_configuraciones_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_configuraciones_updated_at
  BEFORE UPDATE ON configuraciones
  FOR EACH ROW
  EXECUTE FUNCTION update_configuraciones_updated_at();








