-- Tabla para almacenar ubicaciones GPS de técnicos en tiempo real
CREATE TABLE IF NOT EXISTS ubicaciones_tecnicos (
  id bigint generated by default as identity primary key,
  tecnico_id uuid references perfiles(id) on delete cascade,
  ticket_id bigint references tickets(id) on delete set null,
  latitud decimal(10, 8) not null,
  longitud decimal(11, 8) not null,
  ultima_actualizacion timestamptz default now(),
  created_at timestamptz default now()
);

-- Índices para mejor rendimiento
CREATE INDEX IF NOT EXISTS idx_ubicaciones_tecnico_id ON ubicaciones_tecnicos(tecnico_id);
CREATE INDEX IF NOT EXISTS idx_ubicaciones_ticket_id ON ubicaciones_tecnicos(ticket_id);
CREATE INDEX IF NOT EXISTS idx_ubicaciones_ultima_actualizacion ON ubicaciones_tecnicos(ultima_actualizacion DESC);

-- Política RLS: Técnicos pueden insertar/actualizar su propia ubicación, admins pueden ver todas
ALTER TABLE ubicaciones_tecnicos ENABLE ROW LEVEL SECURITY;

-- Técnicos pueden insertar/actualizar su propia ubicación
CREATE POLICY "Técnicos pueden actualizar su ubicación"
  ON ubicaciones_tecnicos FOR ALL
  USING (
    exists (
      select 1 from perfiles
      where perfiles.id = auth.uid()
      and (perfiles.rol = 'tecnico' and perfiles.id = tecnico_id)
    )
  )
  WITH CHECK (
    exists (
      select 1 from perfiles
      where perfiles.id = auth.uid()
      and (perfiles.rol = 'tecnico' and perfiles.id = tecnico_id)
    )
  );

-- Admins pueden ver todas las ubicaciones
CREATE POLICY "Admins pueden ver todas las ubicaciones"
  ON ubicaciones_tecnicos FOR SELECT
  USING (
    exists (
      select 1 from perfiles
      where perfiles.id = auth.uid()
      and perfiles.rol = 'admin'
    )
  );

-- Función para actualizar o insertar ubicación (UPSERT)
CREATE OR REPLACE FUNCTION upsert_ubicacion_tecnico(
  p_tecnico_id uuid,
  p_ticket_id bigint,
  p_latitud decimal,
  p_longitud decimal
)
RETURNS void AS $$
BEGIN
  INSERT INTO ubicaciones_tecnicos (tecnico_id, ticket_id, latitud, longitud, ultima_actualizacion)
  VALUES (p_tecnico_id, p_ticket_id, p_latitud, p_longitud, now())
  ON CONFLICT (tecnico_id) DO UPDATE
  SET
    ticket_id = EXCLUDED.ticket_id,
    latitud = EXCLUDED.latitud,
    longitud = EXCLUDED.longitud,
    ultima_actualizacion = now();
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;




