-- ENUMS para consistencia
create type estado_ticket as enum ('abierto', 'asignado', 'en_proceso', 'espera_repuesto', 'finalizado', 'entregado');

create type prioridad_ticket as enum ('baja', 'normal', 'alta', 'urgente');

-- PERFILES (Usuarios)
create table perfiles (
  id uuid references auth.users primary key,
  email text,
  nombre_completo text,
  rol text check (rol in ('admin', 'ventas', 'tecnico')),
  activo boolean default true,
  created_at timestamptz default now()
);

-- TICKETS PRINCIPALES
create table tickets (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  cliente_nombre text not null,
  cliente_contacto text,
  dispositivo_modelo text,
  falla_declarada text,
  prioridad prioridad_ticket default 'normal',
  estado estado_ticket default 'abierto',
  creado_por uuid references perfiles(id),
  asignado_a uuid references perfiles(id), -- Técnico responsable
  foto_url text -- URL de la foto en Supabase Storage
);

-- REPORTES TÉCNICOS (AI)
create table reportes (
  id bigint generated by default as identity primary key,
  ticket_id bigint references tickets(id) on delete cascade,
  tecnico_id uuid references perfiles(id),
  notas_brutas text, -- Lo que escribió el técnico
  reporte_ia text, -- Lo que generó Gemini (JSON completo)
  repuestos_lista text,
  costo_reparacion decimal(10,2),
  created_at timestamptz default now()
);

-- Índices para mejor rendimiento
create index idx_tickets_estado on tickets(estado);
create index idx_tickets_asignado_a on tickets(asignado_a);
create index idx_tickets_creado_por on tickets(creado_por);
create index idx_reportes_ticket_id on reportes(ticket_id);

-- Función para actualizar updated_at automáticamente
create or replace function update_updated_at_column()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

-- Trigger para actualizar updated_at en tickets
create trigger update_tickets_updated_at
  before update on tickets
  for each row
  execute function update_updated_at_column();

-- Habilitar Realtime para tickets
alter publication supabase_realtime add table tickets;

-- Políticas RLS (Row Level Security)
alter table perfiles enable row level security;
alter table tickets enable row level security;
alter table reportes enable row level security;

-- Política: Todos pueden ver perfiles activos
create policy "Perfiles visibles para todos autenticados"
  on perfiles for select
  using (auth.role() = 'authenticated');

-- Política: Usuarios pueden ver sus propios tickets o tickets asignados
create policy "Tickets visibles según rol"
  on tickets for select
  using (
    auth.uid() = creado_por OR
    auth.uid() = asignado_a OR
    exists (
      select 1 from perfiles
      where perfiles.id = auth.uid()
      and perfiles.rol in ('admin', 'ventas')
    )
  );

-- Política: Ventas y Admin pueden crear tickets
create policy "Crear tickets para ventas y admin"
  on tickets for insert
  with check (
    exists (
      select 1 from perfiles
      where perfiles.id = auth.uid()
      and perfiles.rol in ('admin', 'ventas')
    )
  );

-- Política: Técnicos y Admin pueden actualizar tickets
create policy "Actualizar tickets para técnicos y admin"
  on tickets for update
  using (
    auth.uid() = asignado_a OR
    exists (
      select 1 from perfiles
      where perfiles.id = auth.uid()
      and perfiles.rol = 'admin'
    )
  );

-- Política: Reportes visibles según ticket
create policy "Reportes visibles según ticket"
  on reportes for select
  using (
    exists (
      select 1 from tickets
      where tickets.id = reportes.ticket_id
      and (
        tickets.creado_por = auth.uid() OR
        tickets.asignado_a = auth.uid() OR
        exists (
          select 1 from perfiles
          where perfiles.id = auth.uid()
          and perfiles.rol in ('admin', 'ventas')
        )
      )
    )
  );

-- Política: Técnicos pueden crear reportes
create policy "Crear reportes para técnicos"
  on reportes for insert
  with check (
    auth.uid() = tecnico_id AND
    exists (
      select 1 from tickets
      where tickets.id = reportes.ticket_id
      and tickets.asignado_a = auth.uid()
    )
  );

















